### ISSUE TITLE
Initializer __init__.py is missing in multiple folders 

### ISSUE THREAD

**Issue by MrIndeciso** [io-no/libprovola#1]

**Comment by io-no** [comment]
Hello @MrIndeciso, thank you for diving into libprovola! I've tackled the issue you flagged in what I like to call a "provola style" fix—it's cheesy, effective, and sure to melt away any problems. Let's hope it ages quickly!

Reference to provola number 61fd8f2bd9aad5a6188440edb8cad4aad981d2fa
